// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5sT6G3OFVdVj3bBJrpGNy6vfuihoXLxY',
    appId: '1:47203126535:android:61b9553d54475ce3d7c9a2',
    messagingSenderId: '47203126535',
    projectId: 'wikimagic-2fd4b',
    storageBucket: 'wikimagic-2fd4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeX_5KMnda1hfQlP6UfZFphbZLcTz4BFM',
    appId: '1:47203126535:ios:0c89ef3b678609c9d7c9a2',
    messagingSenderId: '47203126535',
    projectId: 'wikimagic-2fd4b',
    storageBucket: 'wikimagic-2fd4b.appspot.com',
    iosClientId: '47203126535-ilglkpn693qas30sev2vj5euo5s324aa.apps.googleusercontent.com',
    iosBundleId: 'com.icyfeva.wikimagic',
  );
}
